### ISSUE TITLE
Why does a tilemap need a rendering pass?

### ISSUE THREAD

**Issue by pietrovismara** [jonathanrlouie/amethyst-tilemap-demo#1]
First of all, thanks for providing this demo.

I'm still at a very basic level of understanding of how amethyst and rendering works, so forgive me if the question sounds stupid, but I'm curious to understand why a tilemap needs a custom rendering pass. Could you explain that?

**Comment by jonathanrlouie** [comment]
Hi, thanks for asking.

This was written using an older version of Amethyst before there were utilities for drawing sprites, so the example is a bit outdated. While you could still write a custom rendering pass to render a tilemap using a single plane, as was done in this demo, the current version of Amethyst should support a DrawFlat2D render pass, so you should be able to treat each tile as an entity and render a sprite for each tile instead. The [Amethyst book](https://www.amethyst.rs/book/latest/sprites.html) has some sample code for sprite rendering.

**Comment by pietrovismara** [comment]
Thanks for the explanation, I'll check the `DrawFlat2D` render pass then.
